export const baseURL=import.meta.env.VITE_API_URL

const SummaryApi={
   register:{
    url:'/api/user/register',
    method:'post'
   },
   login:{
      url:'/api/user/login',
      method:'post'
   },
   forgot_password:{
      url:'/api/user/forgot-password',
      method:'put'
   },
   verify_forgotPassword_otp:{
      url:'/api/user/verify-forgot-password-otp',
      method:'put'
   },
   reset_password:{
      url:'/api/user/reset-password',
      method:'put'
   },
   refreshToken:{
      url:'/api/user/refresh-token',
      method:'post'
   },
   userDetails:{
      url:'/api/user/user-details',
      method:'get'
   },
   logout:{
      url:'/api/user/logout',
      method:'get'
   },
   updateAvatar:{
      url:'/api/user/upload-avatar',
      method:'put'
   },
   updateUserDetails:{
      url:'/api/user/update-user',
      method:'put'
   },
   addCategory:{
      url:'/api/category/add-category',
      method:'post'
   },
   uploadImage:{
      url:'/api/file/upload',
      method:'post'
   },
   getCategory:{
      url:'/api/category/getCategory',
      method:'get'
   },
   updateCategory:{
      url:"/api/category/update",
      method:'put'
   },
   deleteCategory:{
      url:"/api/category/delete",
      method:'delete'
   },
   createSubCategory:{
      url:"/api/subcategory/add-subcategory",
      method:'post'
   },
   getSubCategory:{
      url:"/api/subcategory/getsubcategory",
      method:'post'
   },
   updateSubCategory:{
      url:"/api/subcategory/updatesubcategory",
      method:'put'
   },
   deleteSubCategory:{
      url:"/api/subcategory/deletesubcategory",
      method:'delete'
   },
   addProduct:{
      url:"/api/product/add-product",
      method:'post'
   },
   getProduct:{
      url:"/api/product/getproduct",
      method:'post'
   },
   getProductByCategory:{
      url:"/api/product/get-product-by-category",
      method:'post'
   },
   getProductByCategoryAndSubCategory:{
      url:"/api/product/get-producy-by-category-and-subcategory",
      method:'post'
   },
   getProductDetails:{
      url:"/api/product/get-product-details",
      method:'post'
   },
   updateProduct:{
      url:"/api/product/update-product",
      method:'put'
   },
   deleteProduct:{
      url:"/api/product/delete-product",
      method:'delete'
   },
   searchProduct:{
      url:"/api/product/search-product",
      method:'post'
   },
   addToCart:{
      url:"/api/cart/create",
      method:'post'
   },
   getCartItem:{
      url:"/api/cart/get",
      method:'get'
   },
   updateCartItemQuantity:{
      url:"/api/cart/update-qty",
      method:'put'
   },
   deleteCartItem:{
      url:"/api/cart/delete-cart-item",
      method:'delete'
   },
   createAddress:{
      url:"/api/address/create-address",
      method:'post',
   },
   getAddress:{
      url:"/api/address/get",
      method:'get'
   },
   updateAddress:{
      url:"/api/address/update",
      method:'put'
   },
   disableAddress:{
      url:"/api/address/disable",
      method:'delete'
   },
   cashOnDeliveryOrder:{
      url:"/api/order/cash-on-delivery",
      method:'post'
   },
   payment_url:{
      url:"/api/order/checkout",
      method:'post'
   },
   getOrderItems:{
      url:"/api/order/order-list",
      method:'get'
   }
}
export default SummaryApi